examples_dir = "./examples"

[capture_maps.clike]
keyword = "keyword"
type = "type"
function = "function"
variable = "variable"
number = "number"
string = "string"
comment = "comment"
operator = "operator"
punctuation = "punctuation"

[capture_maps.hask]
module = "keyword"
import = "keyword"
type = "keyword"
let = "keyword"
in = "keyword"
if = "keyword"
then = "keyword"
else = "keyword"
case = "keyword"
of = "keyword"
TypeName = "type"
Constructor = "type"
FunctionName = "function"
Identifier = "variable"
UpperIdentifier = "type"
Number = "number"
String = "string"
LineComment = "comment"
Operator = "operator"

[capture_maps.talkie]
class = "type"
selector = "function"
variable = "variable"
number = "number"
string = "string"
comment = "comment"
operator = "operator"
punctuation = "punctuation"

[capture_maps.bet]
Inputs = "keyword"
Vars = "keyword"
Variables = "keyword"
Method = "keyword"
Begin = "keyword"
End = "keyword"
If = "keyword"
Then = "keyword"
Else = "keyword"
For = "keyword"
To = "keyword"
While = "keyword"
Buy = "keyword"
Sell = "keyword"
SellShort = "keyword"
BuyToCover = "keyword"
Next = "keyword"
This = "keyword"
Bar = "keyword"
At = "keyword"
On = "keyword"
Market = "keyword"
From = "keyword"
Entry = "keyword"
Contracts = "keyword"
Return = "keyword"
And = "operator"
Or = "operator"
Not = "operator"
Crosses = "operator"
Over = "operator"
Under = "operator"
function_name = "function"
identifier = "variable"
number = "number"
string = "string"
comment = "comment"

[[parsers.talkie_pest]]
adapter = "pest"
grammar_files = ["./examples/talkie-pest/src/talkie.pest"]
highlight_captures = "talkie"

[parsers.talkie_pest.build]
preset = "cargo-wasm-bindgen"
package = "talkie-pest"

[parsers.talkie_pest.runtime]
parse_export = "parse_to_json"

[[parsers.clike_nom]]
adapter = "nom"
grammar_files = ["./examples/clike-nom/src/lib.rs"]
highlight_captures = "clike"

[parsers.clike_nom.build]
preset = "cargo-wasm-bindgen"
package = "clike-nom"

[parsers.clike_nom.runtime]
parse_export = "parse_to_json"

[[parsers.hask_lezer]]
adapter = "lezer"
grammar_files = ["./examples/hask-lezer/src/hask.grammar"]
highlight_captures = "hask"

[parsers.hask_lezer.build]
preset = "lezer"

[parsers.hask_lezer.runtime]
parse_export = "parser"

[[parsers.bet_tree_sitter]]
adapter = "tree-sitter"
grammar_files = ["./examples/bet-tree-sitter/grammar.js"]
highlight_captures = "bet"

[parsers.bet_tree_sitter.build]
preset = "tree-sitter"

[[filetypes.bet]]
extensions = ["*.bet"]
parser = "bet_tree_sitter"
highlight_captures = "bet"

[[filetypes.clike]]
extensions = ["*.clike"]
parser = "clike_nom"
highlight_captures = "clike"

[[filetypes.talkie]]
extensions = ["*.talkie"]
parser = "talkie_pest"
highlight_captures = "talkie"

[[filetypes.hask]]
extensions = ["*.hask"]
parser = "hask_lezer"
highlight_captures = "hask"
